name: Compile Future-MC for PR

on: # Triggers the workflow on pull requests to any branch
  pull_request:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs: # Define build and release
  build:
    name: Build on ubuntu-latest
    runs-on: ubuntu-latest
    steps: # The purpose of this part is to build the file and include it as a build artifact on GitHub and notify trough Discord
      - name: Get repo files
        uses: actions/checkout@v2
      # Can't pass secrets to forks/pulls! So when testing, add your own assets!
      #- name: Adding patches
      #  run: wget ${{ secrets.PATCHES }}
      #- uses: TonyBogdanov/zip@1.0
      #  with:
      #    args: unzip -qq -o ./assets.zip -d ./src/main/resources/assets/futuremc/
      - name: Setup build env
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'gradle'
          java-package: jdk
          check-latest: true
      - name: Compile the best mod for Minecraft?
        run: ./gradlew build --no-daemon
      - name: Remove sources files and get specific jar # We never need the sources jar's and only grep what we want
        run: |
          find -type f -path './build/libs/*' -name '*sources*' -delete
          echo "CFILELOC=$(find ./build/libs/* | grep .jar | head -1)" >> $GITHUB_ENV
      - name: Upload to Github Artifacts tab
        uses: actions/upload-artifact@v2
        with:
          name: FutureMC # This is the name that will appear in the Artifacts tab
          path: "${{ env.CFILELOC }}"
